config/routes.rb
Rails.application.routes.draw do
	root 'images#index'

	resources :images do
		get 'download_file'
		get 'search_word_results'
		get 'search_image_png'
	end
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	# original_uploaded_image
	has_attached_file :associated_image
	has_attached_file :marked_up_image

	validates_attachment :associated_image, presence: true
	validates_attachment_content_type :associated_image, content_type: /\Aimage/
	validates_attachment_file_name :associated_image, matches: [/png\z/]

	validates_attachment_content_type :marked_up_image, content_type: /\Aimage/
	validates_attachment_file_name :marked_up_image, matches: [/png\z/]

	after_save :create_marked_up_image_and_hocr_data_attr

	def create_marked_up_image_and_hocr_data_attr
	    ProcessNewUploadsJob.perform_async(self) unless self.hocr_data
	    # self.update_attributes(CreateBoundingBoxesOnImageProcessingService.new(image: self).call) unless self.hocr_data
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :set_search_word_params, only: [:search_word_results, :search_image_png]
  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  def search_word_results
  end

  def search_image_png
    @file = CreateBoundingBoxesOnImageProcessingService.new({image: @image, search_word: @search_word}).call[:marked_up_image]
    send_data @file.read, type: 'image/png', disposition: 'inline'
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_search_word_params
      @image = Image.find(params[:image_id])
      @search_word = params[:search_word]
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:description, :associated_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, html: {multipart: true} do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :associated_image %>
    <%= f.file_field :associated_image %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/_search_form.html.erb
Search Image for the following Word:
  <%= form_tag image_search_word_results_path(@image), method: :get do %>
      <%= text_field_tag :search_word, params[:search_word] %>
      <%= submit_tag "Search and Return Marked Up Image" %>
  <% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Upload Date</th>      
      <th>Original File Name</th>      
      <th>Original Image</th>
      <th>Download Original Image</th>
      <th>Marked Up Image</th>
      <th>Download Marked Up Image</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.description %></td>
        <td><%= image.created_at.strftime("%B %d, %Y") %></td>
        <td><%= image.associated_image_file_name %></td>
        <td><%= image_tag image.associated_image.url %></td>
        <td><%= link_to 'Download Original Image', image.associated_image.url, download: '' %></td>
        <td><%= image_tag image.marked_up_image.url, alt: "Image is still being processed; thank you for being patient!" %></td>
        <td><%= link_to 'Download Marked Up Image', image.marked_up_image.url, download: '' %></td>
        <td><%= link_to 'Show and Search by Word', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/search_word_results.html.erb
<h3>The word "<%= @search_word %>" has been highlighted in the following image: </h3>

The image, originally named "<%= @image.associated_image_file_name %>" and uploaded on <%= @image.created_at.strftime("%B %d, %Y") %>, can be found in greater detail <%= link_to 'here', image_path(@image) %>.

</br></br>
You can also submit another search:
</br>

<%= render partial: "search_form" %>

<%= image_tag image_search_image_png_path(search_word: @search_word) %> 

<%= link_to 'All Images', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "search_form" %>

<p>
  <strong>File Description:</strong>
  <%= @image.description %>
</p>

<p>
  <strong>File Uploaded At:</strong>
  <%= @image.created_at.strftime("%B %d, %Y") %>
</p>

<p>
  <strong>Original File Name:</strong>
  <%= @image.associated_image_file_name %>
</p>

<p>
  <strong>Original Image:</strong>
	<%= image_tag @image.associated_image.url %>
</p>

<p>
  <strong>Marked Up Image:</strong>
	<%= image_tag @image.marked_up_image.url, alt: "Image is still being processed; thank you for being patient!" %>
</p>

<%= link_to 'Download Original Image', @image.associated_image.url, download: '' %>
<%= link_to 'Download Marked Up Image', @image.marked_up_image.url, download: '' %>
<%= link_to 'Destroy', @image, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'New Image', new_image_path %>
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchProcessSaveImages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>